version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=smartFarm
    volumes:
      - /var/lib/docker/volumes